application: mypreceptor
version: 1-02
runtime: python
api_version: 1

handlers:
- url: /server.*
  script: server.py
- url: /app
  static_dir: app
- url: /fr
  static_dir: fr
- url: /.*
  script: welcome.py
  